<div class="menu">
    <ul id="menu">
        <li>
            <a href="#">Courses Menu</a>
            <ul>
                <li><a href="/bibliothouris/courses/list">List courses</a></li>
                <li><a href="/bibliothouris/courses/register">Register course</a></li>
                <li><a href="/bibliothouris/members/list">List members</a></li>
                <li><a href="/bibliothouris/members/register">Register member</a></li>
            </ul>
        </li>
    </ul>
</div>
